name: TAPL-hs
version: 0.1.0.0
github: "null-lambda/TAPL-hs"

dependencies:
  - base >= 4.7 && < 5
  - parsec
  - megaparsec
  - hashmap
  - mtl

ghc-options:
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N

executables:
  arith:
    main: Main.hs
    source-dirs: "arith"

  untyped:
    main: Main.hs
    source-dirs: "untyped"

  tyarith:
    main: Main.hs
    source-dirs: "tyarith"

  simplebool:
    main: Main.hs
    source-dirs: "simplebool"
    dependencies: 
      - transformers

  fullsimple:
    main: Main.hs
    source-dirs: "fullsimple"