name:                untyped
version:             0.1.0.0
github:              "githubuser/untyped"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

description:         Please see the README on GitHub at <https://github.com/githubuser/untyped#readme>

dependencies:
- base >= 4.7 && < 5
- parsec
- mtl
- transformers

library:
  source-dirs: src

executables:
  untyped-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - untyped
